version: '3'

services:
  api:
    container_name: "api"
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --reload --port=8080 --host=0.0.0.0
    ports:
      - 8080:8080
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: car_database
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  postgres_data:
  pgadmin-data: